/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YaarwinWorkingGiftCodes2026RouteImport } from './routes/yaarwin-working-gift-codes-2026'
import { Route as YaarwinRegisterRouteImport } from './routes/yaarwin-register'
import { Route as YaarwinLoginRouteImport } from './routes/yaarwin-login'
import { Route as YaarwinGiftcodeTodayRouteImport } from './routes/yaarwin-giftcode-today'
import { Route as YaarwinBonusesRouteImport } from './routes/yaarwin-bonuses'
import { Route as YaarwinAgencyProgrammeRouteImport } from './routes/yaarwin-agency-programme'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as GiftCodeGuideRouteImport } from './routes/gift-code-guide'
import { Route as GiftCodeRouteImport } from './routes/gift-code'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContentReviewPolicyRouteImport } from './routes/content-review-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const YaarwinWorkingGiftCodes2026Route =
  YaarwinWorkingGiftCodes2026RouteImport.update({
    id: '/yaarwin-working-gift-codes-2026',
    path: '/yaarwin-working-gift-codes-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const YaarwinRegisterRoute = YaarwinRegisterRouteImport.update({
  id: '/yaarwin-register',
  path: '/yaarwin-register',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinLoginRoute = YaarwinLoginRouteImport.update({
  id: '/yaarwin-login',
  path: '/yaarwin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinGiftcodeTodayRoute = YaarwinGiftcodeTodayRouteImport.update({
  id: '/yaarwin-giftcode-today',
  path: '/yaarwin-giftcode-today',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinBonusesRoute = YaarwinBonusesRouteImport.update({
  id: '/yaarwin-bonuses',
  path: '/yaarwin-bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const YaarwinAgencyProgrammeRoute = YaarwinAgencyProgrammeRouteImport.update({
  id: '/yaarwin-agency-programme',
  path: '/yaarwin-agency-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeGuideRoute = GiftCodeGuideRouteImport.update({
  id: '/gift-code-guide',
  path: '/gift-code-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeRoute = GiftCodeRouteImport.update({
  id: '/gift-code',
  path: '/gift-code',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentReviewPolicyRoute = ContentReviewPolicyRouteImport.update({
  id: '/content-review-policy',
  path: '/content-review-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/content-review-policy': typeof ContentReviewPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-programme': typeof YaarwinAgencyProgrammeRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-login': typeof YaarwinLoginRoute
  '/yaarwin-register': typeof YaarwinRegisterRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/content-review-policy': typeof ContentReviewPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-programme': typeof YaarwinAgencyProgrammeRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-login': typeof YaarwinLoginRoute
  '/yaarwin-register': typeof YaarwinRegisterRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/content-review-policy': typeof ContentReviewPolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download-app': typeof DownloadAppRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/gift-code': typeof GiftCodeRoute
  '/gift-code-guide': typeof GiftCodeGuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/yaarwin-agency-programme': typeof YaarwinAgencyProgrammeRoute
  '/yaarwin-bonuses': typeof YaarwinBonusesRoute
  '/yaarwin-giftcode-today': typeof YaarwinGiftcodeTodayRoute
  '/yaarwin-login': typeof YaarwinLoginRoute
  '/yaarwin-register': typeof YaarwinRegisterRoute
  '/yaarwin-working-gift-codes-2026': typeof YaarwinWorkingGiftCodes2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/content-review-policy'
    | '/disclaimer'
    | '/download-app'
    | '/editorial-policy'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-programme'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-login'
    | '/yaarwin-register'
    | '/yaarwin-working-gift-codes-2026'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/content-review-policy'
    | '/disclaimer'
    | '/download-app'
    | '/editorial-policy'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-programme'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-login'
    | '/yaarwin-register'
    | '/yaarwin-working-gift-codes-2026'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/content-review-policy'
    | '/disclaimer'
    | '/download-app'
    | '/editorial-policy'
    | '/faq'
    | '/games'
    | '/gift-code'
    | '/gift-code-guide'
    | '/how-to-play'
    | '/privacy-policy'
    | '/responsible-gaming'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/yaarwin-agency-programme'
    | '/yaarwin-bonuses'
    | '/yaarwin-giftcode-today'
    | '/yaarwin-login'
    | '/yaarwin-register'
    | '/yaarwin-working-gift-codes-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ContentReviewPolicyRoute: typeof ContentReviewPolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DownloadAppRoute: typeof DownloadAppRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  GiftCodeRoute: typeof GiftCodeRoute
  GiftCodeGuideRoute: typeof GiftCodeGuideRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  YaarwinAgencyProgrammeRoute: typeof YaarwinAgencyProgrammeRoute
  YaarwinBonusesRoute: typeof YaarwinBonusesRoute
  YaarwinGiftcodeTodayRoute: typeof YaarwinGiftcodeTodayRoute
  YaarwinLoginRoute: typeof YaarwinLoginRoute
  YaarwinRegisterRoute: typeof YaarwinRegisterRoute
  YaarwinWorkingGiftCodes2026Route: typeof YaarwinWorkingGiftCodes2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yaarwin-working-gift-codes-2026': {
      id: '/yaarwin-working-gift-codes-2026'
      path: '/yaarwin-working-gift-codes-2026'
      fullPath: '/yaarwin-working-gift-codes-2026'
      preLoaderRoute: typeof YaarwinWorkingGiftCodes2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-register': {
      id: '/yaarwin-register'
      path: '/yaarwin-register'
      fullPath: '/yaarwin-register'
      preLoaderRoute: typeof YaarwinRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-login': {
      id: '/yaarwin-login'
      path: '/yaarwin-login'
      fullPath: '/yaarwin-login'
      preLoaderRoute: typeof YaarwinLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-giftcode-today': {
      id: '/yaarwin-giftcode-today'
      path: '/yaarwin-giftcode-today'
      fullPath: '/yaarwin-giftcode-today'
      preLoaderRoute: typeof YaarwinGiftcodeTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-bonuses': {
      id: '/yaarwin-bonuses'
      path: '/yaarwin-bonuses'
      fullPath: '/yaarwin-bonuses'
      preLoaderRoute: typeof YaarwinBonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yaarwin-agency-programme': {
      id: '/yaarwin-agency-programme'
      path: '/yaarwin-agency-programme'
      fullPath: '/yaarwin-agency-programme'
      preLoaderRoute: typeof YaarwinAgencyProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-code-guide': {
      id: '/gift-code-guide'
      path: '/gift-code-guide'
      fullPath: '/gift-code-guide'
      preLoaderRoute: typeof GiftCodeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-code': {
      id: '/gift-code'
      path: '/gift-code'
      fullPath: '/gift-code'
      preLoaderRoute: typeof GiftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-review-policy': {
      id: '/content-review-policy'
      path: '/content-review-policy'
      fullPath: '/content-review-policy'
      preLoaderRoute: typeof ContentReviewPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ContentReviewPolicyRoute: ContentReviewPolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  DownloadAppRoute: DownloadAppRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  GiftCodeRoute: GiftCodeRoute,
  GiftCodeGuideRoute: GiftCodeGuideRoute,
  HowToPlayRoute: HowToPlayRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  YaarwinAgencyProgrammeRoute: YaarwinAgencyProgrammeRoute,
  YaarwinBonusesRoute: YaarwinBonusesRoute,
  YaarwinGiftcodeTodayRoute: YaarwinGiftcodeTodayRoute,
  YaarwinLoginRoute: YaarwinLoginRoute,
  YaarwinRegisterRoute: YaarwinRegisterRoute,
  YaarwinWorkingGiftCodes2026Route: YaarwinWorkingGiftCodes2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
